// packages/react/src/components/ErrorOverlay.tsx
import React from "react";
import type { SlopMachineError } from "@slopmachine/core";

/**
 * Content to render when generation or loading fails. Either a node, or a
 * function that receives the error and returns a node.
 */
export type SlopErrorFallback =
  React.ReactNode | ((error: SlopMachineError) => React.ReactNode);

interface ErrorOverlayProps {
  error: SlopMachineError;
  errorFallback?: SlopErrorFallback;
  /**
   * Message shown by the default error UI, e.g. "Failed to load image".
   */
  label: string;
}

const overlayStyle: React.CSSProperties = {
  position: "absolute",
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  zIndex: 10,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
};

/**
 * Internal overlay shown over the media slot when generation or loading fails.
 * Renders the consumer's `errorFallback` if provided, otherwise a default message.
 */
export const ErrorOverlay: React.FC<ErrorOverlayProps> = ({
  error,
  errorFallback,
  label,
}) => {
  if (errorFallback !== undefined) {
    return (
      <div
        className="absolute inset-0 z-10 flex items-center justify-center"
        style={overlayStyle}
      >
        {typeof errorFallback === "function"
          ? errorFallback(error)
          : errorFallback}
      </div>
    );
  }

  return (
    <div
      className="absolute inset-0 z-10 flex items-center justify-center bg-muted"
      style={{
        ...overlayStyle,
        backgroundColor: "var(--slop-muted, var(--muted, #f3f4f6))",
      }}
      title={error.message}
    >
      <div
        className="flex flex-col items-center gap-2 text-muted-foreground"
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          gap: "0.5rem",
          color:
            "var(--slop-muted-foreground, var(--muted-foreground, #6b7280))",
        }}
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
          style={{ width: "24px", height: "24px" }}
        >
          <circle cx="12" cy="12" r="10" />
          <line x1="12" y1="8" x2="12" y2="12" />
          <line x1="12" y1="16" x2="12.01" y2="16" />
        </svg>
        <span className="text-xs" style={{ fontSize: "0.75rem" }}>
          {label}
        </span>
      </div>
    </div>
  );
};

// packages/svelte/src/ErrorOverlay.svelte
<!--
  @component
  Internal overlay shown over the media slot when generation or loading fails.
  Renders the consumer's `errorFallback` snippet if provided, otherwise a default message.
-->
<script lang="ts">
  import type { SlopMachineError } from "@slopmachine/core";
  import type { Snippet } from "svelte";

  interface Props {
    error: SlopMachineError;
    errorFallback?: Snippet<[{ error: SlopMachineError }]>;
    /**
     * Message shown by the default error UI, e.g. "Failed to load image".
     */
    label: string;
  }

  let { error, errorFallback, label }: Props = $props();
</script>

{#if errorFallback}
  <div class="overlay">
    {@render errorFallback({ error })}
  </div>
{:else}
  <div class="overlay default" title={error.message}>
    <div class="content">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        aria-hidden="true"
      >
        <circle cx="12" cy="12" r="10"></circle>
        <line x1="12" y1="8" x2="12" y2="12"></line>
        <line x1="12" y1="16" x2="12.01" y2="16"></line>
      </svg>
      <span>{label}</span>
    </div>
  </div>
{/if}

<style>
  .overlay {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    z-index: 10;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .overlay.default {
    background-color: var(--slop-muted, var(--muted, #f3f4f6));
  }

  .content {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.5rem;
    color: var(--slop-muted-foreground, var(--muted-foreground, #6b7280));
  }

  svg {
    width: 24px;
    height: 24px;
  }

  span {
    font-size: 0.75rem;
  }
</style>
