// apps/demo-svelte/src/lib/components/ui/code-block/CodeBlock.svelte
<script lang="ts">
	import { cn } from '$lib/utils';
	import { setContext } from 'svelte';
	import { type BundledLanguage, codeToHtml, type ShikiTransformer } from 'shiki';
	import type { Snippet } from 'svelte';
	import type { HTMLAttributes } from 'svelte/elements';

	interface Props extends HTMLAttributes<HTMLDivElement> {
		code: string;
		language: BundledLanguage;
		showLineNumbers?: boolean;
		wrap?: boolean;
		children?: Snippet;
	}

	let {
		code,
		language,
		showLineNumbers = false,
		wrap = false,
		class: className,
		children,
		...restProps
	}: Props = $props();

	let html = $state('');
	let darkHtml = $state('');

	// Provide code to children (e.g., CodeBlockCopyButton)
	setContext('CodeBlockContext', {
		get code() {
			return code;
		}
	});

	const lineNumberTransformer: ShikiTransformer = {
		name: 'line-numbers',
		line(node, line) {
			node.children.unshift({
				type: 'element',
				tagName: 'span',
				properties: {
					className: [
						'inline-block',
						'min-w-10',
						'mr-4',
						'text-right',
						'select-none',
						'text-muted-foreground'
					]
				},
				children: [{ type: 'text', value: String(line) }]
			});
		}
	};

	async function highlightCode(c: string, l: BundledLanguage, s: boolean) {
		const transformers: ShikiTransformer[] = s ? [lineNumberTransformer] : [];

		const [light, dark] = await Promise.all([
			codeToHtml(c, {
				lang: l,
				theme: 'one-light',
				transformers
			}),
			codeToHtml(c, {
				lang: l,
				theme: 'one-dark-pro',
				transformers
			})
		]);
		return { light, dark };
	}

	$effect(() => {
		let active = true;
		highlightCode(code, language, showLineNumbers).then(({ light, dark }) => {
			if (active) {
				html = light;
				darkHtml = dark;
			}
		});
		return () => {
			active = false;
		};
	});
</script>

<div
	class={cn(
		'group relative w-full overflow-hidden rounded-md border bg-background dark:bg-neutral-950 text-foreground',
		className
	)}
	{...restProps}
>
	<div class="relative">
		<div
			class={cn(
				'overflow-auto dark:hidden [&>pre]:m-0 [&>pre]:bg-background dark:[&>pre]:bg-neutral-950! [&>pre]:p-4 [&>pre]:text-foreground! [&>pre]:text-sm [&_code]:font-mono [&_code]:text-sm',
				wrap && '[&>pre]:whitespace-pre-wrap [&>pre]:wrap-break-word'
			)}
		>
			{@html html}
		</div>
		<div
			class={cn(
				'hidden overflow-auto dark:block [&>pre]:m-0 [&>pre]:bg-background dark:[&>pre]:bg-neutral-950! [&>pre]:p-4 [&>pre]:text-foreground! [&>pre]:text-sm [&_code]:font-mono [&_code]:text-sm',
				wrap && '[&>pre]:whitespace-pre-wrap [&>pre]:wrap-break-word'
			)}
		>
			{@html darkHtml}
		</div>
		{#if children}
			<div class="absolute top-2 right-2 flex items-center gap-2">
				{@render children()}
			</div>
		{/if}
	</div>
</div>

// demo/src/components/ui/code-block.tsx
import { cn } from "@/lib/utils";
import { CheckIcon, CopyIcon } from "lucide-react";
import {
  type ComponentProps,
  createContext,
  type HTMLAttributes,
  useContext,
  useEffect,
  useRef,
  useState,
} from "react";
import { type BundledLanguage, codeToHtml, type ShikiTransformer } from "shiki";
import { Button } from "./button";

type CodeBlockProps = HTMLAttributes<HTMLDivElement> & {
  code: string;
  language: BundledLanguage;
  showLineNumbers?: boolean;
  wrap?: boolean;
};

interface CodeBlockContextType {
  code: string;
}

const CodeBlockContext = createContext<CodeBlockContextType>({
  code: "",
});

const lineNumberTransformer: ShikiTransformer = {
  name: "line-numbers",
  line(node, line) {
    node.children.unshift({
      type: "element",
      tagName: "span",
      properties: {
        className: [
          "inline-block",
          "min-w-10",
          "mr-4",
          "text-right",
          "select-none",
          "text-muted-foreground",
        ],
      },
      children: [{ type: "text", value: String(line) }],
    });
  },
};

export async function highlightCode(
  code: string,
  language: BundledLanguage,
  showLineNumbers = false,
) {
  const transformers: ShikiTransformer[] = showLineNumbers
    ? [lineNumberTransformer]
    : [];

  return await Promise.all([
    codeToHtml(code, {
      lang: language,
      theme: "one-light",
      transformers,
    }),
    codeToHtml(code, {
      lang: language,
      theme: "one-dark-pro",
      transformers,
    }),
  ]);
}

export const CodeBlock = ({
  code,
  language,
  showLineNumbers = false,
  wrap = false,
  className,
  children,
  ...props
}: CodeBlockProps) => {
  const [html, setHtml] = useState<string>("");
  const [darkHtml, setDarkHtml] = useState<string>("");
  const mounted = useRef(false);

  useEffect(() => {
    highlightCode(code, language, showLineNumbers).then(([light, dark]) => {
      if (!mounted.current) {
        setHtml(light);
        setDarkHtml(dark);
        mounted.current = true;
      }
    });

    return () => {
      mounted.current = false;
    };
  }, [code, language, showLineNumbers]);

  return (
    <CodeBlockContext.Provider value={{ code }}>
      <div
        className={cn(
          "group relative w-full overflow-hidden rounded-md border bg-background text-foreground",
          className,
        )}
        {...props}>
        <div className="relative">
          <div
            className={cn(
              "overflow-auto dark:hidden [&>pre]:m-0 [&>pre]:bg-background! [&>pre]:p-4 [&>pre]:text-foreground! [&>pre]:text-sm [&_code]:font-mono [&_code]:text-sm",
              wrap && "[&>pre]:whitespace-pre-wrap [&>pre]:wrap-break-word",
            )}
            dangerouslySetInnerHTML={{ __html: html }}
          />
          <div
            className={cn(
              "hidden overflow-auto dark:block [&>pre]:m-0 [&>pre]:bg-background! [&>pre]:p-4 [&>pre]:text-foreground! [&>pre]:text-sm [&_code]:font-mono [&_code]:text-sm",
              wrap && "[&>pre]:whitespace-pre-wrap [&>pre]:wrap-break-word",
            )}
            dangerouslySetInnerHTML={{ __html: darkHtml }}
          />
          {children && (
            <div className="absolute top-2 right-2 flex items-center gap-2">
              {children}
            </div>
          )}
        </div>
      </div>
    </CodeBlockContext.Provider>
  );
};

export type CodeBlockCopyButtonProps = ComponentProps<typeof Button> & {
  onCopy?: () => void;
  onError?: (error: Error) => void;
  timeout?: number;
};

export const CodeBlockCopyButton = ({
  onCopy,
  onError,
  timeout = 2000,
  children,
  className,
  ...props
}: CodeBlockCopyButtonProps) => {
  const [isCopied, setIsCopied] = useState(false);
  const { code } = useContext(CodeBlockContext);

  const copyToClipboard = async () => {
    if (typeof window === "undefined" || !navigator?.clipboard?.writeText) {
      onError?.(new Error("Clipboard API not available"));
      return;
    }

    try {
      await navigator.clipboard.writeText(code);
      setIsCopied(true);
      onCopy?.();
      setTimeout(() => setIsCopied(false), timeout);
    } catch (error) {
      onError?.(error as Error);
    }
  };

  const Icon = isCopied ? CheckIcon : CopyIcon;

  return (
    <Button
      className={cn("shrink-0", className)}
      onClick={copyToClipboard}
      size="icon"
      variant="ghost"
      {...props}>
      {children ?? <Icon size={14} />}
    </Button>
  );
};

/** Demo component for preview */
export default function CodeBlockDemo() {
  const code = `function MyComponent(props) {
  return (
    <div>
      <h1>Hello, {props.name}!</h1>
      <p>This is an example React component.</p>
    </div>
  );
}`;

  return (
    <div className="w-full max-w-2xl p-6">
      <CodeBlock code={code} language="jsx">
        <CodeBlockCopyButton
          onCopy={() => console.log("Copied code to clipboard")}
          onError={() => console.error("Failed to copy code to clipboard")}
        />
      </CodeBlock>
    </div>
  );
}
